#!/bin/bash
rm -r in/images/1/*  					> /dev/null 2>&1 
rm -r in/xml/1/*.xml  					> /dev/null 2>&1 
rm -r in/xml/1/*.XML  					> /dev/null 2>&1 
rm -r in/xml/1/delta/*  				> /dev/null 2>&1 
rm -r out/bow/top/sift/100/1/*  		> /dev/null 2>&1 
rm -r out/bow/top/sift/200/1/*  		> /dev/null 2>&1 
rm -r out/bow/top/color/100/1/*  		> /dev/null 2>&1 
rm -r out/bow/top/color/200/1/*  		> /dev/null 2>&1 
rm -r out/bow/webpage/color/100/1/*  	> /dev/null 2>&1 
rm -r out/bow/webpage/color/200/1/*  	> /dev/null 2>&1 
rm -r out/bow/webpage/sift/100/1/*  	> /dev/null 2>&1 
rm -r out/bow/webpage/sift/200/1/*  	> /dev/null 2>&1 
rm -r out/hsv/top/1/*  					> /dev/null 2>&1 
rm -r out/hsv/webpage/1/*  				> /dev/null 2>&1 
rm -r out/sift/top/1/*  				> /dev/null 2>&1 
rm -r out/sift/webpage/1/*  			> /dev/null 2>&1 
rm -r out/M.txt  						> /dev/null 2>&1 
rm -r out/images/1/*  					> /dev/null 2>&1 
